---
- hosts: exp

  tasks:

    - name: Add /usr/local/bin to Securing path
      replace:
        dest: /etc/sudoers
#        state: present
#        backrefs: yes
#       regexp: '^(.*)secure_path = /(.*)$'
#        line: 'Defaults    secure_path = /usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin'
        regexp: '^(.*)(secure_path = )(/sbin:)(.*)$'
        replace: '\1\2/usr/local/bin:\3\4'
        validate: 'visudo -cf %s'

