---
- hosts: exp

  tasks:
    - name: remove the Docker package
      yum:
        name: "{{ packages }}"
        state: absent
      vars:
        packages:
          - docker
          - docker-client
          - docker-client-latest
          - docker-common
          - docker-latest
          - docker-latest-logrotate
          - docker-logrotate
          - docker-selinux
          - docker-engine-selinux

    - name: install additional packet
      yum:
        name: "{{ packages2 }}"
        state: latest
      vars:
        packages2:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2


    - name: Add docker Repo
      shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

 
    - name: install Docker-CE
      yum:
        name: docker-ce
        state: latest
