---
- hosts: exp
  vars:
    docker__machine_version: v0.15.0
    docker__machine_download_url: https://github.com/docker/machine/releases/download/{{ docker__machine_version }}/docker-machine-Linux-x86_64
#                                 https://github.com/docker/machine/releases/download/v0.15.0/docker-machine-
  tasks:

    - name: Remove Docker Machine
      file:
        path: "/usr/local/bin/docker-machine"
        state: "absent"
      tags: 
        - remove_dm

    - name: Install Docker Machinee
      get_url:
        url: "{{ docker__machine_download_url }}"
        dest: "/usr/local/bin/docker-machine"
        force: true
        owner: "root"
        group: "root"
        mode: "0755"
      tags: 
        - install_dm

#curl -L https://github.com/docker/machine/releases/download/v0.15.0/docker-machine-$(uname -s)-$(uname -m) >/tmp/docker-machine &&
#    chmod +x /tmp/docker-machine &&
#        sudo cp /tmp/docker-machine /usr/local/bin/docker-machine