---
- hosts: exp

  tasks:

  - name: Creat chatbot group
    group:
      name: chatbot
    tags: 
      - creat_chatbot_group
  
  - name: Creat chatbot user
    user:
      name: chatbot
      shell: /bin/bash
      group: chatbot
      groups: wheel
      append: yes
      createhome: yes
      state: present
      password: "$6$saltsalt$Tc2rpGCJdnwMfFmUiJp/1uKoUivRymfkeX1z63KVCEMOvl9vQIarImROu.USyY.pWaO.jitO80BPtlC8H.py.."
#      generate_ssh_key: yes
#      ssh_key_bits: 2048
#      ssh_key_file: .ssh/id_rsa
#      expires: -1
    tags: 
      - creat_chatbot_user
      
  - name: Creat directories
    file:
      path: "{{ item.path }}"
      state: directory
      mode: "{{ item.mode }}"
      owner: "{{ item.user }}"
      group: "{{ item.group }}"
    tags: 
      -creat_bot_dir
    with_items:
      - { path: '/opt/chatbot', group: 'chatbot', user: 'chatbot', mode: '775' }
      - { path: '/var/log/bot', group: 'chatbot', user: 'chatbot', mode: '775' }
      - { path: '/opt/chatbot/logstash', group: 'chatbot', user: 'chatbot', mode: '775' }
      - { path: '/var/lib/postgresql/oauth', group: 'chatbot', user: 'chatbot', mode: '775' }
      - { path: '/var/lib/postgresql/thebot', group: 'chatbot', user: 'chatbot', mode: '775' }
      - { path: '/var/lib/postgresql/atm', group: 'chatbot', user: 'chatbot', mode: '775' }
      - { path: '/var/lib/postgresql/bank', group: 'chatbot', user: 'chatbot', mode: '775' }
      - { path: '/var/lib/postgresql/currency', group: 'chatbot', user: 'chatbot', mode: '775' }
      - { path: '/var/lib/postgresql/history', group: 'chatbot', user: 'chatbot', mode: '775' }
      - { path: '/var/lib/postgresql/markup', group: 'chatbot', user: 'chatbot', mode: '775' }
      - { path: '/var/lib/rabbitmq', group: 'chatbot', user: 'chatbot', mode: '755' }
      
