---
- hosts: exp

  tasks:
    - name: Make sure we have a wheel group
      group:
        name: wheel
      state: present

    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
      tags:
        - enable_wheel  

    - name: Add sudoers users to wheel group
      user: name=chatbot groups=wheel append=yes state=present createhome=yes
      tags:
        - chatbot_wheel

