---
- hosts: exp

  tasks:
    - name: remove Docker
      yum:
        name: "{{ packages }}"
        state: absent
      vars:
        packages:
          - docker
          - docker-client
          - docker-common
      tags:
        - remove_docker
        
    - name: remove Docker-ce
      yum:
        name: "{{ packages }}"
        state: absent
      vars:
        packages:
          - docker-ce
      tags:
        - remove_docker-ce
 
    - name: install Docker-CE
      yum:
        name: docker-ce
        state: latest
      tags:
        - install_docker-ce      

    - name: install Docker
      yum:
        name: docker
        state: latest
      tags:
        - install_docker      

    - name: Start and Enable Docker Service
      service:
        name: docker
        state: started
        enabled: yes
      tags:
        - start_docker

#    - name: list installed
#      yum:
#        list: 
#          - docker
#          - docker-ce
#      register: result
#      tags:
#        - list_packets

    - name: yum_command 
      yum:
#        name: docker
        list=installed
      register: yum_packages
      tags:
        - list_packets
        
    - debug: var=item
      with_items: "{{yum_packages|json_query(jsonquery)}}"
      vars:
        jsonquery: "results[?name=='docker-ce'].version"
#        var: yum_packages
      tags:
        - list_packets

